/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.meetspeaklearn.grammarmanager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class AdjectivalCategoryTable extends javax.swing.JPanel {
    
    private AdjectivalCategory category;
    private ArrayList<Adjective> adjectives;

    /**
     * Creates new form AdjectivalCategoryTable
     */
    public AdjectivalCategoryTable() {
        initComponents();
    }
    
    public AdjectivalCategoryTable(AdjectivalCategory category) {
        this();
        this.category = category;
        adjectives = new ArrayList<Adjective>();
        
        categoryLabel.setText(category.getName());
        
        ArrayList<String> adjNames = category.getAdjectiveNames();
        System.out.println("adjNames.size()=" + adjNames.size());
        
        if (category.getAdjectives()!= null) {
            adjectives.addAll(category.getAdjectives());
        }
        
        Collections.sort(adjectives, Adjective.getComparator());
        table.setModel(new AdjectivalCategoryTableModel(4, adjectives));
        table.setDefaultRenderer(Adjective.class, new AdjectiveRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adjectiveTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        categoryLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table.setModel(new AdjectivalCategoryTableModel(4, adjectives));
        table.setRowHeight(20);
        table.setRowSelectionAllowed(false);
        table.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableMouseMoved(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableMouseExited(evt);
            }
        });
        adjectiveTable.setViewportView(table);

        add(adjectiveTable, java.awt.BorderLayout.CENTER);

        categoryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(0, 51, 204));
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoryLabel.setText("Category");
        categoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoryLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoryLabelMouseExited(evt);
            }
        });
        add(categoryLabel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void categoryLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryLabelMouseEntered

    private void categoryLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryLabelMouseExited

    private void tableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseMoved

    private void tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseEntered

    private void tableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseExited

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        int col = table.getSelectedColumn();
        System.out.println("tableMouseClicked(): " + row + ", " + col);
        
        Adjective adj = (Adjective) table.getValueAt(row, col);
        AdjectiveSiblingFlagsPanel flagsPanel = new AdjectiveSiblingFlagsPanel(adj);
        flagsPanel.setLocationRelativeTo(this);
        flagsPanel.setVisible(true);
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane adjectiveTable;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
