/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.meetspeaklearn.grammarmanager;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author steve
 */
public class AdjectiveTable extends javax.swing.JPanel {
    private ArrayList<Adjective> adjectives;

    /** Creates new form AdjectiveTable */
    public AdjectiveTable() {
        initComponents();
        
        table.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    
    public AdjectiveTable(ArrayList<Adjective> adjectives) {
        this();
        
        setAdjectives(adjectives);
    }
    
    public void setAdjectives(Collection<Adjective> adjectives) {
        this.adjectives = new ArrayList<Adjective>();
        this.adjectives.addAll(adjectives);
        
        ArrayList<String> adjNames = new ArrayList<String>();
        
        for (Adjective adj : this.adjectives) adjNames.add(adj.getText());
        
        Collections.sort(this.adjectives, Adjective.getComparator());
        table.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table.setModel(new AdjectivalCategoryTableModel(4, this.adjectives));
        table.setDefaultRenderer(Adjective.class, new AdjectiveRenderer());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adjectiveTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table.setModel(new AdjectivalCategoryTableModel(4, adjectives));
        table.setRowHeight(20);
        table.setRowSelectionAllowed(false);
        table.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableMouseMoved(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableMouseExited(evt);
            }
        });
        adjectiveTable.setViewportView(table);

        add(adjectiveTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseMoved

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseEntered

    private void tableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane adjectiveTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
