/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.meetspeaklearn.grammarmanager;

import java.util.*;

import net.meetspeaklearn.ui.component.CheckBoxList;
import net.meetspeaklearn.util.listener.*;

/**
 *
 * @author steve
 */
public class AdjectiveExclusionFrame
        extends javax.swing.JFrame
        implements ICollectionModifier, IListItemSelectedListener {
    
    private ArrayList<ICollectionModifiedListener> listeners
            = new ArrayList<ICollectionModifiedListener>();
    private ArrayList<Adjective> inheritedAdjectives;
    private HashSet<Adjective> exludedAdjectives;
    
    private CheckBoxList checkBoxList;

    /**
     * Creates new form AdjectiveExclusionFrame
     */
    public AdjectiveExclusionFrame() {
        initComponents();
        inheritedAdjectives = new ArrayList<Adjective>();
        exludedAdjectives = new HashSet<Adjective>();
    }
    
    public AdjectiveExclusionFrame(HashSet<Adjective> inheritedAdjectives, HashSet<Adjective> exludedAdjectives) {
        initComponents();
        
        this.inheritedAdjectives = new ArrayList<Adjective>();
        this.inheritedAdjectives.addAll(inheritedAdjectives);
        Collections.sort(this.inheritedAdjectives, Adjective.getComparator());
        
        this.exludedAdjectives = new HashSet<Adjective>();
        this.exludedAdjectives.addAll(exludedAdjectives);
        
        checkBoxList = new CheckBoxList();
        adjectivesPanel.remove(placeHolderPanel);
        adjectivesPanel.add(checkBoxList, java.awt.BorderLayout.CENTER);
        
        for (Adjective adj : this.inheritedAdjectives) {
            checkBoxList.addItem(adj.getText(), adj, exludedAdjectives.contains(adj));
            System.out.println("Added: " + adj.getText());
        }
        
        checkBoxList.addListener(this);
        
        adjectivesPanel.invalidate();
        adjectivesScrollPane.revalidate();
    }
    
    public void addListener(ICollectionModifiedListener listener) {
        listeners.add(listener);
    }
    
    public void removeListener(ICollectionModifiedListener listener) {
        listeners.remove(listener);        
    }
    
    public void itemSelected(Object item, boolean selectionState) {
        System.out.println("AdjectiveExclusionFrame.itemSelected(): item=" + item + ", selectionState=" + selectionState);
        if (selectionState)
            this.exludedAdjectives.add((Adjective) item);
        else
            this.exludedAdjectives.remove((Adjective) item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        excludeButton = new javax.swing.JButton();
        adjectivesScrollPane = new javax.swing.JScrollPane();
        adjectivesPanel = new javax.swing.JPanel();
        placeHolderPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 850));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Exclude Adjectives");
        getContentPane().add(titleLabel, java.awt.BorderLayout.PAGE_START);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        excludeButton.setText("Exclude");
        excludeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excludeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(excludeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        adjectivesScrollPane.setPreferredSize(new java.awt.Dimension(200, 800));

        adjectivesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Inherited Adjectives (tick to exclude)"));
        adjectivesPanel.setPreferredSize(new java.awt.Dimension(1000, 4000));
        adjectivesPanel.setLayout(new java.awt.BorderLayout(10, 10));

        placeHolderPanel.setBackground(new java.awt.Color(204, 0, 0));
        placeHolderPanel.setMinimumSize(new java.awt.Dimension(1000, 4000));
        placeHolderPanel.setName(""); // NOI18N
        placeHolderPanel.setPreferredSize(new java.awt.Dimension(1000, 4000));
        adjectivesPanel.add(placeHolderPanel, java.awt.BorderLayout.CENTER);

        adjectivesScrollPane.setViewportView(adjectivesPanel);

        getContentPane().add(adjectivesScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void excludeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excludeButtonActionPerformed
        for (ICollectionModifiedListener listener : listeners)
            listener.collectionModified(exludedAdjectives);
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_excludeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdjectiveExclusionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdjectiveExclusionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdjectiveExclusionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdjectiveExclusionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdjectiveExclusionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adjectivesPanel;
    private javax.swing.JScrollPane adjectivesScrollPane;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton excludeButton;
    private javax.swing.JPanel placeHolderPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
