/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.meetspeaklearn.grammarmanager;

import static net.meetspeaklearn.grammarmanager.WorkingDataManager.workingLexicon;

import java.util.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author steve
 */
public class AssignAcademicLevelFrame extends javax.swing.JFrame {
    private ArrayList<Lex> selectedLexemes;
    private AcademicLevel selectedLevel;
    private Lex current;
    private int count;
    private int index;

    /**
     * Creates new form AssignUnassignedLexemesFrame
     */
    public AssignAcademicLevelFrame() {
        initComponents();
        // filterComboBox
        filterComboBox.setModel(new DefaultComboBoxModel<String>(AcademicLevel.valuesAsStrings()));
        filterComboBox.setSelectedItem(AcademicLevel.UNASSIGNED.toString());
        selectedLevel = AcademicLevel.UNASSIGNED;
        selectedLexemes = workingLexicon.getAllLexemes(selectedLevel);
        count = selectedLexemes.size();
        index = 0;
        displayCurrent();
    }
    
    private void displayCurrent() {
        if ((count > 0) && (index < count)) {
            current = selectedLexemes.get(index);
            this.lexemeName.setText("\"" + current.getLexeme() + "\"");
        } else {
            current = null;
            this.lexemeName.setText("No more lexemes...");
        }
    }
    
    private void nextLexeme() {
        if ((count > 0) && (index < count))
            index += 1;
        
        displayCurrent();
    }
    
    private void previousLexeme() {
        if ((count > 0) && (index > 0))
            index -= 1;
        
        displayCurrent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lexemePanel = new javax.swing.JPanel();
        controlsPanel = new javax.swing.JPanel();
        beginnerButton = new javax.swing.JButton();
        intermediateButton = new javax.swing.JButton();
        advancedButton = new javax.swing.JButton();
        unassignedButton = new javax.swing.JButton();
        lexemeNamePanel = new javax.swing.JPanel();
        lexemeName = new javax.swing.JLabel();
        definitionPanel = new javax.swing.JPanel();
        definitionScrollPane = new javax.swing.JScrollPane();
        definitionTextArea = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        skipButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lexemePanel.setLayout(new java.awt.BorderLayout());

        controlsPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        controlsPanel.setMinimumSize(new java.awt.Dimension(200, 63));
        controlsPanel.setPreferredSize(new java.awt.Dimension(200, 250));
        controlsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 30));

        beginnerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beginnerButton.setText("Beginner");
        beginnerButton.setPreferredSize(new java.awt.Dimension(120, 23));
        beginnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerButtonActionPerformed(evt);
            }
        });
        controlsPanel.add(beginnerButton);

        intermediateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        intermediateButton.setText("Intermediate");
        intermediateButton.setPreferredSize(new java.awt.Dimension(120, 23));
        intermediateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermediateButtonActionPerformed(evt);
            }
        });
        controlsPanel.add(intermediateButton);

        advancedButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        advancedButton.setText("Advanced");
        advancedButton.setPreferredSize(new java.awt.Dimension(120, 23));
        advancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedButtonActionPerformed(evt);
            }
        });
        controlsPanel.add(advancedButton);

        unassignedButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unassignedButton.setText("Unassigned");
        unassignedButton.setPreferredSize(new java.awt.Dimension(120, 23));
        unassignedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unassignedButtonActionPerformed(evt);
            }
        });
        controlsPanel.add(unassignedButton);

        lexemePanel.add(controlsPanel, java.awt.BorderLayout.CENTER);

        lexemeNamePanel.setPreferredSize(new java.awt.Dimension(200, 250));

        lexemeName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lexemeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lexemeName.setText("lexeme name");
        lexemeName.setPreferredSize(new java.awt.Dimension(180, 22));
        lexemeNamePanel.add(lexemeName);

        definitionPanel.setPreferredSize(new java.awt.Dimension(180, 200));
        definitionPanel.setLayout(new java.awt.BorderLayout());

        definitionTextArea.setColumns(20);
        definitionTextArea.setRows(5);
        definitionScrollPane.setViewportView(definitionTextArea);

        definitionPanel.add(definitionScrollPane, java.awt.BorderLayout.CENTER);

        lexemeNamePanel.add(definitionPanel);

        lexemePanel.add(lexemeNamePanel, java.awt.BorderLayout.WEST);

        getContentPane().add(lexemePanel, java.awt.BorderLayout.CENTER);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(backButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        skipButton.setText("Skip");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(skipButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Assign Academic Level");
        topPanel.add(titleLabel);

        filterComboBox.setPreferredSize(new java.awt.Dimension(200, 22));
        filterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterComboBoxActionPerformed(evt);
            }
        });
        topPanel.add(filterComboBox);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void beginnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerButtonActionPerformed
        if (current != null) {
            current.setLevel(AcademicLevel.BEGINNER);
            nextLexeme();
        }
    }//GEN-LAST:event_beginnerButtonActionPerformed

    private void intermediateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermediateButtonActionPerformed
        if (current != null) {
            current.setLevel(AcademicLevel.INTERMEDIATE);
            nextLexeme();
        }
    }//GEN-LAST:event_intermediateButtonActionPerformed

    private void advancedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedButtonActionPerformed
        if (current != null) {
            current.setLevel(AcademicLevel.ADVANCED);
            nextLexeme();
        }
    }//GEN-LAST:event_advancedButtonActionPerformed

    private void unassignedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unassignedButtonActionPerformed
        if (current != null) {
            current.setLevel(AcademicLevel.UNASSIGNED);
            nextLexeme();
        }
    }//GEN-LAST:event_unassignedButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        previousLexeme();
    }//GEN-LAST:event_backButtonActionPerformed

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        nextLexeme();
    }//GEN-LAST:event_skipButtonActionPerformed

    private void filterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterComboBoxActionPerformed
        String selectedItem = (String) filterComboBox.getSelectedItem();
        selectedLevel = AcademicLevel.fromString(selectedItem);
        selectedLexemes = workingLexicon.getAllLexemes(selectedLevel);
        count = selectedLexemes.size();
        index = 0;
        displayCurrent();
    }//GEN-LAST:event_filterComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignAcademicLevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignAcademicLevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignAcademicLevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignAcademicLevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignAcademicLevelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advancedButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton beginnerButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel definitionPanel;
    private javax.swing.JScrollPane definitionScrollPane;
    private javax.swing.JTextArea definitionTextArea;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JButton intermediateButton;
    private javax.swing.JLabel lexemeName;
    private javax.swing.JPanel lexemeNamePanel;
    private javax.swing.JPanel lexemePanel;
    private javax.swing.JButton skipButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton unassignedButton;
    // End of variables declaration//GEN-END:variables
}
