/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.meetspeaklearn.grammarmanager;

import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author steve
 */
public class CreateLexicon extends javax.swing.JFrame {

    /**
     * Creates new form CreateLexicon
     */
    public CreateLexicon() {
        initComponents();
        languageCodeComboBox.setModel(new DefaultComboBoxModel<String>(Language.LANGUAGE_CODE.valuesAsString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        lexiconNameLabel = new javax.swing.JLabel();
        lexiconNameTextField = new javax.swing.JTextField();
        languageCodeLabel = new javax.swing.JLabel();
        languageCodeComboBox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Lexicon");

        centerPanel.setLayout(new java.awt.GridLayout(2, 2, 0, 6));

        lexiconNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lexiconNameLabel.setText("Lexicon name:");
        centerPanel.add(lexiconNameLabel);

        lexiconNameTextField.setText("Enter New Lexicon Name");
        centerPanel.add(lexiconNameTextField);

        languageCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        languageCodeLabel.setText("Language code:");
        centerPanel.add(languageCodeLabel);

        languageCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        centerPanel.add(languageCodeComboBox);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(createButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if (GrammarManangerFrame.createLexiconDialog != null) {
            GrammarManangerFrame.createLexiconDialog.setVisible(false);
            GrammarManangerFrame.createLexiconDialog.dispose();
            GrammarManangerFrame.createLexiconDialog = null;
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        WorkingDataManager manager = WorkingDataManager.currentWorkingDataManager;
        int index = languageCodeComboBox.getSelectedIndex();
        String languageCodeAsString = (index != -1) ? languageCodeComboBox.getItemAt(index) : null;
        String lexiconName = lexiconNameTextField.getText();
        boolean languageCodeSupplied = true;
        boolean lexiconNameSupplied = true;
        String errorString = "";

        if (languageCodeAsString == null) {
            languageCodeSupplied = false;
            errorString += "Language code was not povided.\n";
        } else if (languageCodeAsString.compareTo("") == 0) {
            languageCodeSupplied = false;
            errorString += "Language code was not povided.\n";
        }

        if (lexiconName == null) {
            lexiconNameSupplied = false;
            errorString += "Lexicon name was not povided.\n";
        } else if (lexiconName.compareTo("") == 0) {
            lexiconNameSupplied = false;
            errorString += "Lexicon name was not povided.\n";
        }

        if ((! languageCodeSupplied) || (! lexiconNameSupplied)) {
            showMessageDialog(this, errorString);
            return;
        }

        Lexicon lexicon = (Lexicon) GrammarObject.instantiate(GrammarObject.GO_CLASS.LEXICON);

        lexicon.setLanguageCodeAsString(languageCodeAsString);
        lexicon.setName(lexiconName);

        String message = manager.AddOrReplaceLexicon(lexicon);

        showMessageDialog(this, message);
        
        WorkingDataManager.workingLexicon = lexicon;

        if (GrammarManangerFrame.createLexiconDialog != null) {
            GrammarManangerFrame.createLexiconDialog.setVisible(false);
            GrammarManangerFrame.createLexiconDialog.dispose();
            GrammarManangerFrame.createLexiconDialog = null;
        }
    }//GEN-LAST:event_createButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLexicon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLexicon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLexicon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLexicon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLexicon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox<String> languageCodeComboBox;
    private javax.swing.JLabel languageCodeLabel;
    private javax.swing.JLabel lexiconNameLabel;
    private javax.swing.JTextField lexiconNameTextField;
    // End of variables declaration//GEN-END:variables
}
