/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.meetspeaklearn.grammarmanager;

import javax.swing.DefaultComboBoxModel;
import java.awt.event.WindowEvent;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author steve
 */
public class CreateLanguage extends javax.swing.JFrame {

    /**
     * Creates new form CreateLanguage
     */
    public CreateLanguage() {
        initComponents();
        languageCodeComboBox.setModel(new DefaultComboBoxModel<String>(Language.LANGUAGE_CODE.valuesAsString()));
        genderDivisionSystemTypeComboBox.setModel(new DefaultComboBoxModel<String>(Language.GENDER_DIVISION_SYSTEM_TYPE.valuesAsString()));
        nameTextField.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        languageCodeLabel = new javax.swing.JLabel();
        languageCodeComboBox = new javax.swing.JComboBox<>();
        genderDivisionSystemTypeLabel = new javax.swing.JLabel();
        genderDivisionSystemTypeComboBox = new javax.swing.JComboBox<>();
        bottomPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Language");
        setName("Create Language"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(6, 6));

        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(rightPanel, java.awt.BorderLayout.LINE_END);

        centerPanel.setLayout(new java.awt.GridLayout(3, 2, 0, 6));

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Language name:");
        centerPanel.add(nameLabel);
        nameLabel.getAccessibleContext().setAccessibleName("nameLabel");

        nameTextField.setText("Enter Language Name");
        centerPanel.add(nameTextField);

        languageCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        languageCodeLabel.setText("Language code:");
        centerPanel.add(languageCodeLabel);

        languageCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        centerPanel.add(languageCodeComboBox);

        genderDivisionSystemTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genderDivisionSystemTypeLabel.setText("Gender division system type:");
        centerPanel.add(genderDivisionSystemTypeLabel);

        genderDivisionSystemTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        centerPanel.add(genderDivisionSystemTypeComboBox);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(cancelButton);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(createButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if (GrammarManangerFrame.createLanguageDialog != null) {
            GrammarManangerFrame.createLanguageDialog.setVisible(false);
            GrammarManangerFrame.createLanguageDialog.dispose();
            GrammarManangerFrame.createLanguageDialog = null;
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        WorkingDataManager manager = WorkingDataManager.currentWorkingDataManager;
        int index = languageCodeComboBox.getSelectedIndex();
        String languageCodeAsString = (index != -1) ? languageCodeComboBox.getItemAt(index) : null;
        String languageName = nameTextField.getText();
        index = genderDivisionSystemTypeComboBox.getSelectedIndex();
        String gdsTypeAsString =  (index != -1) ? genderDivisionSystemTypeComboBox.getItemAt(index) : null;
        boolean languageCodeSupplied = true;
        boolean languageNameSupplied = true;
        boolean gdsTypeSupplied = true;
        String errorString = "";
        
        if (languageCodeAsString == null) {
            languageCodeSupplied = false;
            errorString += "Language code was not povided.\n";
        } else if (languageCodeAsString.compareTo("") == 0) {
            languageCodeSupplied = false;
            errorString += "Language code was not povided.\n";
        }
        
        if (languageName == null) {
            languageNameSupplied = false;
            errorString += "Language name was not povided.\n";
        } else if (languageName.compareTo("") == 0) {
            languageNameSupplied = false;
            errorString += "Language name was not povided.\n";
        }
        
        if (gdsTypeAsString == null) {
            gdsTypeSupplied = false;
            errorString += "Gender division system type was not povided.\n";
        } else if (gdsTypeAsString.compareTo("") == 0) {
            gdsTypeSupplied = false;
            errorString += "Gender division system type was not povided.\n";
        }
        
        if ((! languageCodeSupplied) || (! languageNameSupplied) || (! gdsTypeSupplied)) {
            showMessageDialog(this, errorString);
            return;
        }
        
        
        Language language = new Language();
        
        language.setLanguageCodeAsString(languageCodeAsString);
        language.setName(languageName);
        language.setGenderDivisionTypeAsString(gdsTypeAsString);
        
        String message = manager.AddOrReplaceLanguage(language);
        
        showMessageDialog(this, message);
        
        if (GrammarManangerFrame.createLanguageDialog != null) {
            GrammarManangerFrame.createLanguageDialog.setVisible(false);
            GrammarManangerFrame.createLanguageDialog.dispose();
            GrammarManangerFrame.createLanguageDialog = null;
        }
    }//GEN-LAST:event_createButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLanguage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox<String> genderDivisionSystemTypeComboBox;
    private javax.swing.JLabel genderDivisionSystemTypeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> languageCodeComboBox;
    private javax.swing.JLabel languageCodeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
