/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.meetspeaklearn.grammarmanager;

import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author steve
 */
public class RenameLexeme extends javax.swing.JFrame {
    private GrammarManangerFrame gm;
    private Lexicon lexicon;
    private Lex lexeme;

    /**
     * Creates new form RenameLexeme
     */
    public RenameLexeme() {
        initComponents();
    }
    
    public RenameLexeme(GrammarManangerFrame gm, Lexicon lexicon, Lex lexeme) {
        this();
        this.gm = gm;
        this.lexeme = lexeme;
        this.lexicon = lexicon;
        
        lexemeTextField.setText(lexeme.getLexeme());
        newLexemeNameTextField.selectAll();
        createButton.setEnabled(false);
    }

    public Lex getLexeme() {
        return lexeme;
    }

    public void setLexeme(Lex lexeme) {
        this.lexeme = lexeme;
    }

    public Lexicon getLexicon() {
        return lexicon;
    }

    public void setLexicon(Lexicon lexicon) {
        this.lexicon = lexicon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        lexemeLabel = new javax.swing.JLabel();
        lexemeTextField = new javax.swing.JTextField();
        lexemeLabel1 = new javax.swing.JLabel();
        newLexemeNameTextField = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rename Lexeme");

        centerPanel.setLayout(new java.awt.GridLayout(2, 2, 6, 6));

        lexemeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lexemeLabel.setText("Old Name for Lexeme:");
        centerPanel.add(lexemeLabel);

        lexemeTextField.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        lexemeTextField.setFocusable(false);
        lexemeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexemeTextFieldActionPerformed(evt);
            }
        });
        lexemeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lexemeTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lexemeTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lexemeTextFieldKeyTyped(evt);
            }
        });
        centerPanel.add(lexemeTextField);

        lexemeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lexemeLabel1.setText("New Name for Lexeme:");
        centerPanel.add(lexemeLabel1);

        newLexemeNameTextField.setText("Enter text here");
        newLexemeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLexemeNameTextFieldActionPerformed(evt);
            }
        });
        newLexemeNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newLexemeNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newLexemeNameTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newLexemeNameTextFieldKeyTyped(evt);
            }
        });
        centerPanel.add(newLexemeNameTextField);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(cancelButton);

        createButton.setText("Rename");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(createButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lexemeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexemeTextFieldActionPerformed

    }//GEN-LAST:event_lexemeTextFieldActionPerformed

    private void lexemeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lexemeTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lexemeTextFieldKeyPressed

    private void lexemeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lexemeTextFieldKeyReleased
        
    }//GEN-LAST:event_lexemeTextFieldKeyReleased

    private void lexemeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lexemeTextFieldKeyTyped

    }//GEN-LAST:event_lexemeTextFieldKeyTyped

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String text = newLexemeNameTextField.getText();
        String messageIfFailed = lexicon.rename(lexeme, text);

        if (messageIfFailed != null) {
            showMessageDialog(this, messageIfFailed);
            newLexemeNameTextField.selectAll();
            createButton.setEnabled(false);
            return;
        } else {
            createButton.setEnabled(true);
        }

        if (gm != null) {
            gm.updateView();
            gm.selectLexeme(lexeme);
        }

        setVisible(false);
        dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void newLexemeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLexemeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newLexemeNameTextFieldActionPerformed

    private void newLexemeNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newLexemeNameTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_newLexemeNameTextFieldKeyPressed

    private void newLexemeNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newLexemeNameTextFieldKeyReleased
        String text = newLexemeNameTextField.getText();

        if (lexicon.isInterned(text)) {
            newLexemeNameTextField.setForeground(Color.red);
            createButton.setEnabled(false);
        } else {
            newLexemeNameTextField.setForeground(Color.black);
            createButton.setEnabled(true);
        }
    }//GEN-LAST:event_newLexemeNameTextFieldKeyReleased

    private void newLexemeNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newLexemeNameTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newLexemeNameTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RenameLexeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RenameLexeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RenameLexeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RenameLexeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenameLexeme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel lexemeLabel;
    private javax.swing.JLabel lexemeLabel1;
    private javax.swing.JTextField lexemeTextField;
    private javax.swing.JTextField newLexemeNameTextField;
    // End of variables declaration//GEN-END:variables
}
