/* Author: Stephen DeVoy*/

#ifndef MACROS_HEADER

#define MACROS_HEADER

#define CHECK_POINTERS 1
#if CHECK_POINTERS
#define CHECK_POINTER(FUNCNAME, PTR, RET) \
{if (PTR == 0) {fprintf(stderr, "\n%s(): %s is null.", #FUNCNAME, #PTR); RET;}}
#define CHECK_POINTER2(FUNCNAME, PTR1, PTR2, RET) \
{CHECK_POINTER(FUNCNAME, PTR1, RET) \
 CHECK_POINTER(FUNCNAME, PTR2, RET)}
#define CHECK_POINTER3(FUNCNAME, PTR1, PTR2, PTR3, RET) \
{CHECK_POINTER(FUNCNAME, PTR1, RET) \
 CHECK_POINTER(FUNCNAME, PTR2, RET) \
 CHECK_POINTER(FUNCNAME, PTR3, RET)}
#else
#define CHECK_POINTER(FUNCNAME, PTR, RET)
#define CHECK_POINTER2(FUNCNAME, PTR1, PTR2, RET)
#define CHECK_POINTER3(FUNCNAME, PTR1, PTR2, PTR3, RET)
#endif
#endif 